name: Test with TL 2022

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: maclotsen/texlive:2022
          shell: bash
          options: --rm -i -v ${{ github.workspace }}:/build
          run: |
            make -C trunk test
      - name: Archive Test results (2022)
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: build
          path: ${{ github.workspace }}
